###
GET http://localhost:4000/api/clients/

###
GET http://localhost:4000/api/bicycles/

####
POST http://localhost:4000/api/clients
Content-Type: application/json

{
    "name": "Miguel Zamora",
    "email": "miguelzamora.23.97@gmail.com",
    "phone": "1345334765432",
    "age": 23,
    "sex": "Male"
}

####
POST http://localhost:4000/api/bicycles/
Content-Type: application/json

{
    "price": 2000,
    "model": "aquila",
    "brand": "Optimus",
    "type": "Montañera",
    "size": "Rin 29",
    "material": "Acero"
}

###
GET http://localhost:4000/api/clients/601cdfdffb57762308c5664d

###
DELETE http://localhost:4000/api/clients/601bb724b969e32bd43e6746

###
PUT http://localhost:4000/api/clients/601cdfdffb57762308c5664d
Content-Type: application/json

{
    "phone": "684769739583"
}

###
GET http://localhost:4000/api/clientscount

###
GET http://localhost:4000/api/bicyclescount
